### ISSUE TITLE
scaner in supercruse deplys hardpoints

### ISSUE THREAD

**Issue by TomW1605** [DrParanoia/Aurora#2]
for some reason when using the scaner in super cruse it thinks hardpoints are deployed and flashes that key but also turns off the jump key

**Comment by TomW1605** [comment]
i think i actualy fixed this in my branch by adding a negative filter for when in supercruse

**Comment by DrParanoia** [comment]
This is actually how the game works. Also, on the radar you can see ships with deployed hardpoints as triangles even is supercruise (FSD Interdicor anyone?).

**Comment by TomW1605** [comment]
the problem isent so much that it shows that hardpoints are deployed but that it furns off the light for the jump key esentialy saying that i cant jump. i havent used an interdictor in ages but if i rememember corectly you can still jump with it deployed. if this is infact the case then i segest that the hardpoint key still flashes but also the jump key is still lit.
