### ISSUE TITLE
make the background change with the hud mode

### ISSUE THREAD

**Issue by TomW1605** [DrParanoia/Aurora#4]
make the background change with the hud mode. also if posable make the hud colour key (and background) change based on those obscure colour settings in the some file somwhere.

**Comment by DrParanoia** [comment]
What do you mean exactly? Are we talking about Discovery/Combat HUD modes? Also, the HUD key is changing color depending on the hud mode.

**Comment by TomW1605** [comment]
i know the HUD key changes. i mean make the background to the same colour (but dim)

**Comment by DrParanoia** [comment]
Implemented in aaca81c727c665a5f7e6c427dc75db06890ae7ca ;)
